---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$(whoami)/public_html/
    - /bin/cp -R index.html $DEPLOYPATH
    - /bin/cp -R style.css $DEPLOYPATH
    - /bin/cp -R script.js $DEPLOYPATH
    - /bin/cp -R README.md $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
